<?php


namespace Database\Seeders;

use App\Models\ItemMaster;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ItemMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $items = [
            // Food Items
            [
                'name' => 'Margherita Pizza',
                'unicode_name' => 'Margherita Pizza',
                'item_category_id' => 1,
                'item_code' => 'FD-001',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 10,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 150.00,
                'selling_price' => 350.00,
                'is_menu_item' => true,
                'additional_notes' => 'Classic pizza with tomato and mozzarella',
                'description' => 'Traditional Italian pizza',
                'attributes' => [
                    'ingredients' => 'Dough, Tomato Sauce, Mozzarella Cheese, Basil',
                    'img' => 'margherita.jpg',
                    'prep_time' => 15,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Pepperoni Pizza',
                'unicode_name' => 'Pepperoni Pizza',
                'item_category_id' => 1,
                'item_code' => 'FD-002',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 10,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 180.00,
                'selling_price' => 400.00,
                'is_menu_item' => true,
                'additional_notes' => 'Classic pizza with pepperoni',
                'description' => 'Traditional Italian pizza with pepperoni',
                'attributes' => [
                    'ingredients' => 'Dough, Tomato Sauce, Mozzarella Cheese, Pepperoni',
                    'img' => 'pepperoni.jpg',
                    'prep_time' => 15,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => true,
                    'discounts' => 10.00
                ],
            ],
            [
                'name' => 'Hawaiian Pizza',
                'unicode_name' => 'Hawaiian Pizza',
                'item_category_id' => 1,
                'item_code' => 'FD-003',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 8,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 170.00,
                'selling_price' => 380.00,
                'is_menu_item' => true,
                'additional_notes' => 'Pizza with ham and pineapple',
                'description' => 'Controversial but delicious pineapple pizza',
                'attributes' => [
                    'ingredients' => 'Dough, Tomato Sauce, Mozzarella Cheese, Ham, Pineapple',
                    'img' => 'hawaiian.jpg',
                    'prep_time' => 15,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Vegetarian Pizza',
                'unicode_name' => 'Vegetarian Pizza',
                'item_category_id' => 1,
                'item_code' => 'FD-004',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 8,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 160.00,
                'selling_price' => 370.00,
                'is_menu_item' => true,
                'additional_notes' => 'Vegetarian pizza with fresh vegetables',
                'description' => 'Healthy vegetarian option',
                'attributes' => [
                    'ingredients' => 'Dough, Tomato Sauce, Mozzarella Cheese, Bell Peppers, Mushrooms, Olives, Onions',
                    'img' => 'vegetarian.jpg',
                    'prep_time' => 15,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'BBQ Chicken Pizza',
                'unicode_name' => 'BBQ Chicken Pizza',
                'item_category_id' => 1,
                'item_code' => 'FD-005',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 8,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 190.00,
                'selling_price' => 420.00,
                'is_menu_item' => true,
                'additional_notes' => 'Pizza with BBQ sauce and chicken',
                'description' => 'American-style BBQ chicken pizza',
                'attributes' => [
                    'ingredients' => 'Dough, BBQ Sauce, Mozzarella Cheese, Chicken, Red Onions, Cilantro',
                    'img' => 'bbq-chicken.jpg',
                    'prep_time' => 15,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => true,
                    'discounts' => 15.00
                ],
            ],
            [
                'name' => 'Classic Cheeseburger',
                'unicode_name' => 'Classic Cheeseburger',
                'item_category_id' => 1,
                'item_code' => 'FD-006',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 15,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 120.00,
                'selling_price' => 280.00,
                'is_menu_item' => true,
                'additional_notes' => 'Classic American cheeseburger',
                'description' => 'Juicy beef patty with cheese',
                'attributes' => [
                    'ingredients' => 'Beef Patty, Burger Bun, Cheese, Lettuce, Tomato, Onion, Pickles, Ketchup, Mustard',
                    'img' => 'cheeseburger.jpg',
                    'prep_time' => 10,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Bacon Cheeseburger',
                'unicode_name' => 'Bacon Cheeseburger',
                'item_category_id' => 1,
                'item_code' => 'FD-007',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 12,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 150.00,
                'selling_price' => 320.00,
                'is_menu_item' => true,
                'additional_notes' => 'Cheeseburger with crispy bacon',
                'description' => 'Classic burger with bacon',
                'attributes' => [
                    'ingredients' => 'Beef Patty, Burger Bun, Cheese, Bacon, Lettuce, Tomato, Onion, Mayo',
                    'img' => 'bacon-cheeseburger.jpg',
                    'prep_time' => 12,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => true,
                    'discounts' => 10.00
                ],
            ],
            [
                'name' => 'Chicken Burger',
                'unicode_name' => 'Chicken Burger',
                'item_category_id' => 1,
                'item_code' => 'FD-008',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 15,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 110.00,
                'selling_price' => 250.00,
                'is_menu_item' => true,
                'additional_notes' => 'Spicy chicken burger with mayo',
                'description' => 'Crispy chicken burger',
                'attributes' => [
                    'ingredients' => 'Chicken Patty, Burger Bun, Lettuce, Tomato, Mayo',
                    'img' => 'chicken-burger.jpg',
                    'prep_time' => 10,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Veggie Burger',
                'unicode_name' => 'Veggie Burger',
                'item_category_id' => 1,
                'item_code' => 'FD-009',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 10,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 90.00,
                'selling_price' => 220.00,
                'is_menu_item' => true,
                'additional_notes' => 'Plant-based burger patty',
                'description' => 'Vegetarian burger option',
                'attributes' => [
                    'ingredients' => 'Veggie Patty, Burger Bun, Lettuce, Tomato, Onion, Special Sauce',
                    'img' => 'veggie-burger.jpg',
                    'prep_time' => 8,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Double Cheeseburger',
                'unicode_name' => 'Double Cheeseburger',
                'item_category_id' => 1,
                'item_code' => 'FD-010',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 8,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 180.00,
                'selling_price' => 380.00,
                'is_menu_item' => true,
                'additional_notes' => 'Two beef patties with double cheese',
                'description' => 'For those with big appetites',
                'attributes' => [
                    'ingredients' => '2 Beef Patties, Burger Bun, 2 Cheese Slices, Lettuce, Tomato, Onion, Pickles, Special Sauce',
                    'img' => 'double-cheeseburger.jpg',
                    'prep_time' => 12,
                    'portion_size' => 'large',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => true,
                    'discounts' => 20.00
                ],
            ],
            [
                'name' => 'Caesar Salad',
                'unicode_name' => 'Caesar Salad',
                'item_category_id' => 1,
                'item_code' => 'FD-011',
                'unit_of_measurement' => 'bowl',
                'reorder_level' => 15,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 80.00,
                'selling_price' => 220.00,
                'is_menu_item' => true,
                'additional_notes' => 'Classic Caesar salad with chicken option',
                'description' => 'Romaine lettuce with Caesar dressing',
                'attributes' => [
                    'ingredients' => 'Romaine Lettuce, Croutons, Parmesan Cheese, Caesar Dressing',
                    'img' => 'caesar-salad.jpg',
                    'prep_time' => 8,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'add_ons' => ['Grilled Chicken (+LKR 80)', 'Shrimp (+LKR 120)']
                ],
            ],
            [
                'name' => 'Greek Salad',
                'unicode_name' => 'Greek Salad',
                'item_category_id' => 1,
                'item_code' => 'FD-012',
                'unit_of_measurement' => 'bowl',
                'reorder_level' => 12,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 90.00,
                'selling_price' => 240.00,
                'is_menu_item' => true,
                'additional_notes' => 'Fresh Mediterranean salad',
                'description' => 'Traditional Greek salad with feta',
                'attributes' => [
                    'ingredients' => 'Cucumber, Tomato, Red Onion, Olives, Feta Cheese, Olive Oil',
                    'img' => 'greek-salad.jpg',
                    'prep_time' => 10,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Caprese Salad',
                'unicode_name' => 'Caprese Salad',
                'item_category_id' => 1,
                'item_code' => 'FD-013',
                'unit_of_measurement' => 'plate',
                'reorder_level' => 10,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 100.00,
                'selling_price' => 260.00,
                'is_menu_item' => true,
                'additional_notes' => 'Italian mozzarella and tomato salad',
                'description' => 'Simple and fresh Italian salad',
                'attributes' => [
                    'ingredients' => 'Fresh Mozzarella, Tomato, Basil, Balsamic Glaze, Olive Oil',
                    'img' => 'caprese-salad.jpg',
                    'prep_time' => 5,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Chicken Wings (6 pcs)',
                'unicode_name' => 'Chicken Wings (6 pcs)',
                'item_category_id' => 1,
                'item_code' => 'FD-014',
                'unit_of_measurement' => 'plate',
                'reorder_level' => 20,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 150.00,
                'selling_price' => 320.00,
                'is_menu_item' => true,
                'additional_notes' => 'Choice of buffalo, BBQ or teriyaki',
                'description' => 'Crispy chicken wings',
                'attributes' => [
                    'ingredients' => 'Chicken Wings, Sauce (choice of Buffalo, BBQ, Teriyaki), Celery Sticks, Blue Cheese Dip',
                    'img' => 'chicken-wings.jpg',
                    'prep_time' => 12,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => true,
                    'discounts' => 15.00,
                    'options' => ['Buffalo', 'BBQ', 'Teriyaki']
                ],
            ],
            [
                'name' => 'Mozzarella Sticks (6 pcs)',
                'unicode_name' => 'Mozzarella Sticks (6 pcs)',
                'item_category_id' => 1,
                'item_code' => 'FD-015',
                'unit_of_measurement' => 'plate',
                'reorder_level' => 15,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 120.00,
                'selling_price' => 280.00,
                'is_menu_item' => true,
                'additional_notes' => 'Fried mozzarella sticks with marinara',
                'description' => 'Crispy fried cheese sticks',
                'attributes' => [
                    'ingredients' => 'Mozzarella Cheese, Bread Crumbs, Marinara Sauce',
                    'img' => 'mozzarella-sticks.jpg',
                    'prep_time' => 8,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'French Fries',
                'unicode_name' => 'French Fries',
                'item_category_id' => 1,
                'item_code' => 'FD-016',
                'unit_of_measurement' => 'plate',
                'reorder_level' => 25,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 40.00,
                'selling_price' => 120.00,
                'is_menu_item' => true,
                'additional_notes' => 'Classic crispy fries',
                'description' => 'Golden fried potato fries',
                'attributes' => [
                    'ingredients' => 'Potatoes, Salt, Oil',
                    'img' => 'french-fries.jpg',
                    'prep_time' => 6,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'options' => ['Regular', 'Large (+LKR 40)']
                ],
            ],
            [
                'name' => 'Onion Rings',
                'unicode_name' => 'Onion Rings',
                'item_category_id' => 1,
                'item_code' => 'FD-017',
                'unit_of_measurement' => 'plate',
                'reorder_level' => 15,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 60.00,
                'selling_price' => 150.00,
                'is_menu_item' => true,
                'additional_notes' => 'Crispy fried onion rings',
                'description' => 'Battered and fried onion rings',
                'attributes' => [
                    'ingredients' => 'Onions, Batter, Oil',
                    'img' => 'onion-rings.jpg',
                    'prep_time' => 8,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Garlic Bread',
                'unicode_name' => 'Garlic Bread',
                'item_category_id' => 1,
                'item_code' => 'FD-018',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 20,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 30.00,
                'selling_price' => 90.00,
                'is_menu_item' => true,
                'additional_notes' => 'Toasted bread with garlic butter',
                'description' => 'Classic garlic bread',
                'attributes' => [
                    'ingredients' => 'Bread, Garlic Butter, Parsley',
                    'img' => 'garlic-bread.jpg',
                    'prep_time' => 5,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Cheese Garlic Bread',
                'unicode_name' => 'Cheese Garlic Bread',
                'item_category_id' => 1,
                'item_code' => 'FD-019',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 20,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 50.00,
                'selling_price' => 120.00,
                'is_menu_item' => true,
                'additional_notes' => 'Garlic bread with melted cheese',
                'description' => 'Garlic bread with cheese topping',
                'attributes' => [
                    'ingredients' => 'Bread, Garlic Butter, Mozzarella Cheese, Parsley',
                    'img' => 'cheese-garlic-bread.jpg',
                    'prep_time' => 7,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Chicken Quesadilla',
                'unicode_name' => 'Chicken Quesadilla',
                'item_category_id' => 1,
                'item_code' => 'FD-020',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 12,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 130.00,
                'selling_price' => 290.00,
                'is_menu_item' => true,
                'additional_notes' => 'Grilled tortilla with chicken and cheese',
                'description' => 'Mexican-style quesadilla',
                'attributes' => [
                    'ingredients' => 'Tortilla, Chicken, Cheese, Bell Peppers, Onions, Sour Cream, Salsa',
                    'img' => 'chicken-quesadilla.jpg',
                    'prep_time' => 10,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Spaghetti Bolognese',
                'unicode_name' => 'Spaghetti Bolognese',
                'item_category_id' => 1,
                'item_code' => 'FD-021',
                'unit_of_measurement' => 'plate',
                'reorder_level' => 15,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 140.00,
                'selling_price' => 320.00,
                'is_menu_item' => true,
                'additional_notes' => 'Classic Italian pasta with meat sauce',
                'description' => 'Traditional spaghetti with meat sauce',
                'attributes' => [
                    'ingredients' => 'Spaghetti, Ground Beef, Tomato Sauce, Onions, Garlic, Herbs, Parmesan Cheese',
                    'img' => 'spaghetti-bolognese.jpg',
                    'prep_time' => 12,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Fettuccine Alfredo',
                'unicode_name' => 'Fettuccine Alfredo',
                'item_category_id' => 1,
                'item_code' => 'FD-022',
                'unit_of_measurement' => 'plate',
                'reorder_level' => 12,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 130.00,
                'selling_price' => 300.00,
                'is_menu_item' => true,
                'additional_notes' => 'Creamy Alfredo pasta',
                'description' => 'Rich and creamy pasta dish',
                'attributes' => [
                    'ingredients' => 'Fettuccine, Cream, Butter, Parmesan Cheese, Garlic, Parsley',
                    'img' => 'fettuccine-alfredo.jpg',
                    'prep_time' => 10,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Penne Arrabiata',
                'unicode_name' => 'Penne Arrabiata',
                'item_category_id' => 1,
                'item_code' => 'FD-023',
                'unit_of_measurement' => 'plate',
                'reorder_level' => 12,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 120.00,
                'selling_price' => 280.00,
                'is_menu_item' => true,
                'additional_notes' => 'Spicy tomato pasta',
                'description' => 'Penne pasta with spicy tomato sauce',
                'attributes' => [
                    'ingredients' => 'Penne, Tomato Sauce, Garlic, Chili, Olive Oil, Basil',
                    'img' => 'penne-arrabiata.jpg',
                    'prep_time' => 10,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Chicken Tikka Masala',
                'unicode_name' => 'Chicken Tikka Masala',
                'item_category_id' => 1,
                'item_code' => 'FD-024',
                'unit_of_measurement' => 'plate',
                'reorder_level' => 15,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 160.00,
                'selling_price' => 350.00,
                'is_menu_item' => true,
                'additional_notes' => 'Popular Indian curry dish',
                'description' => 'Grilled chicken in creamy tomato sauce',
                'attributes' => [
                    'ingredients' => 'Chicken, Yogurt, Cream, Tomato, Spices, Butter',
                    'img' => 'chicken-tikka-masala.jpg',
                    'prep_time' => 15,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => true,
                    'discounts' => 10.00
                ],
            ],
            [
                'name' => 'Butter Chicken',
                'unicode_name' => 'Butter Chicken',
                'item_category_id' => 1,
                'item_code' => 'FD-025',
                'unit_of_measurement' => 'plate',
                'reorder_level' => 15,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 170.00,
                'selling_price' => 370.00,
                'is_menu_item' => true,
                'additional_notes' => 'Classic Indian butter chicken',
                'description' => 'Creamy tomato-based chicken curry',
                'attributes' => [
                    'ingredients' => 'Chicken, Butter, Cream, Tomato, Spices',
                    'img' => 'butter-chicken.jpg',
                    'prep_time' => 15,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],
            [
                'name' => 'Dal Makhani',
                'unicode_name' => 'Dal Makhani',
                'item_category_id' => 1,
                'item_code' => 'FD-026',
                'unit_of_measurement' => 'bowl',
                'reorder_level' => 15,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 90.00,
                'selling_price' => 220.00,
                'is_menu_item' => true,
                'additional_notes' => 'Creamy lentil curry',
                'description' => 'Slow-cooked black lentils with butter and cream',
                'attributes' => [
                    'ingredients' => 'Black Lentils, Kidney Beans, Butter, Cream, Spices',
                    'img' => 'dal-makhani.jpg',
                    'prep_time' => 10,
                    'portion_size' => 'regular',
                    'available_from' => '11:00:00',
                    'available_to' => '23:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'discounts' => 0.00
                ],
            ],

            // Beverage Items
            [
                'name' => 'Iced Coffee',
                'unicode_name' => 'Iced Coffee',
                'item_category_id' => 2,
                'item_code' => 'BV-001',
                'unit_of_measurement' => 'glass',
                'reorder_level' => 20,
                'is_perishable' => true,
                'shelf_life_in_days' => 1,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 30.00,
                'selling_price' => 120.00,
                'is_menu_item' => true,
                'additional_notes' => 'Cold brewed coffee',
                'description' => 'Refreshing iced coffee',
                'attributes' => [
                    'ingredients' => 'Coffee, Milk, Ice, Sugar',
                    'img' => 'iced-coffee.jpg',
                    'prep_time' => 5,
                    'portion_size' => 'regular',
                    'available_from' => '08:00:00',
                    'available_to' => '22:00:00',
                    'available_days' => 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
                    'promotions' => false,
                    'variants' => ['Regular', 'Large']
                ],
            ],

            // Cleaning Supplies
            [
                'name' => 'Dishwashing Liquid',
                'unicode_name' => 'Dishwashing Liquid',
                'item_category_id' => 3,
                'item_code' => 'CS-001',
                'unit_of_measurement' => 'bottle',
                'reorder_level' => 5,
                'is_perishable' => false,
                'shelf_life_in_days' => 365,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 200.00,
                'selling_price' => 300.00,
                'is_menu_item' => false,
                'additional_notes' => '500ml bottle',
                'description' => 'Concentrated dishwashing liquid',
                'attributes' => [
                    'brand' => 'CleanPro',
                    'volume' => '500ml',
                    'fragrance' => 'Lemon',
                    'img' => 'dishwash-liquid.jpg'
                ],
            ],

            // Kitchen Equipment
            [
                'name' => 'Chef Knife',
                'unicode_name' => 'Chef Knife',
                'item_category_id' => 4,
                'item_code' => 'KE-001',
                'unit_of_measurement' => 'piece',
                'reorder_level' => 2,
                'is_perishable' => false,
                'shelf_life_in_days' => null,
                'branch_id' => 1,
                'organization_id' => 1,
                'buying_price' => 1500.00,
                'selling_price' => 2500.00,
                'is_menu_item' => false,
                'additional_notes' => '8-inch stainless steel',
                'description' => 'Professional chef knife',
                'attributes' => [
                    'brand' => 'KitchenPro',
                    'material' => 'Stainless Steel',
                    'length' => '8 inches',
                    'warranty' => '2 years',
                    'img' => 'chef-knife.jpg'
                ],
            ]
        ];

        foreach ($items as $item) {
            ItemMaster::firstOrCreate(
                ['item_code' => $item['item_code']], // Check by unique item code
                $item // Create with all data if not exists
            );
        }

        $this->command->info("  Total Items in the database : " . ItemMaster::count());
        $this->command->info("  ✅ Item Master seeded successfully!");
    }
}
