@extends('errors.generic')

@section('errorTitle', 'Page Not Found')
@section('errorCode', '404')
@section('errorHeading', 'Page Not Found')
@section('errorMessage', 'The page you are looking for could not be found.')
@section('headerClass', 'bg-gradient-warning')
@section('errorIcon', 'fas fa-map-marker-alt')
@section('mainIcon', 'fas fa-map-marker-alt')
@section('iconBgClass', 'bg-yellow-100')
@section('iconColor', 'text-yellow-500')
@section('buttonClass', 'bg-[#FF9800] hover:bg-[#e68a00]')
