<?php

// auth routes - Generated by RouteGroupsExport
// Generated on: 2025-06-25 17:20:45
// Total routes: 1

use Illuminate\Support\Facades\Route;

Route::get('login', App\Http\Controllers\AdminAuthController@showLoginForm)->middleware(['web'])->name('login');
