<?php

// guest routes - Generated by RouteGroupsExport
// Generated on: 2025-06-25 17:20:45
// Total routes: 17

use Illuminate\Support\Facades\Route;

Route::guestGroup(function () {
    Route::get('guest/menu', App\Http\Controllers\Guest\GuestController@viewMenu)->name('menu.index');
    Route::get('guest/menu/date/{date}', App\Http\Controllers\Guest\GuestController@viewMenuByDate)->name('menu.date');
    Route::get('guest/menu/special', App\Http\Controllers\Guest\GuestController@viewSpecialMenu)->name('menu.special');
    Route::post('guest/cart/add', App\Http\Controllers\Guest\GuestController@addToCart)->name('cart.add');
    Route::post('guest/cart/update', App\Http\Controllers\Guest\GuestController@updateCart)->name('cart.update');
    Route::delete('guest/cart/remove/{itemId}', App\Http\Controllers\Guest\GuestController@removeFromCart)->name('cart.remove');
    Route::get('guest/cart', App\Http\Controllers\Guest\GuestController@viewCart)->name('cart.view');
    Route::delete('guest/cart/clear', App\Http\Controllers\Guest\GuestController@clearCart)->name('cart.clear');
    Route::post('guest/order/create', App\Http\Controllers\Guest\GuestController@createOrder)->name('order.create');
    Route::get('guest/order/{orderNumber}/track', App\Http\Controllers\Guest\GuestController@trackOrder)->name('order.track');
    Route::get('guest/order/{orderNumber}/details', App\Http\Controllers\Guest\GuestController@orderDetails)->name('order.details');
    Route::get('guest/reservation/create', App\Http\Controllers\Guest\GuestController@createReservation)->name('reservation.create');
    Route::post('guest/reservation/store', App\Http\Controllers\Guest\GuestController@storeReservation)->name('reservation.store');
    Route::get('guest/reservation/{confirmationCode}/details', App\Http\Controllers\Guest\GuestController@reservationDetails)->name('reservation.details');
    Route::get('guest/session/info', App\Http\Controllers\Guest\GuestController@sessionInfo)->name('session.info');
    Route::get('guest/order/confirmation', App\Http\Controllers\GuestController@order)->name('order.confirmation');
    Route::get('guest/reservation/confirmation', App\Http\Controllers\GuestController@reservation)->name('reservation.confirmation');
});
