import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://restaurent-management-sysytem.test/admin/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('superadmin@rms.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('SuperAdmin123!');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: ' Subscriptions ' }).click();
  await page.getByRole('link', { name: '+ Create Plan' }).nth(1).click();
  await page.getByRole('textbox', { name: 'Plan Name *' }).click();
  await page.getByRole('textbox', { name: 'Plan Name *' }).fill('Pro Plan');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Plan With Full Modules');
  await page.getByText('Complete order processing and').click();
  await page.getByRole('checkbox', { name: 'Reservation System Table' }).check();
  await page.getByRole('checkbox', { name: 'Inventory Management Stock' }).check();
  await page.getByRole('checkbox', { name: 'Menu Management Menu items,' }).check();
  await page.getByRole('checkbox', { name: 'Customer Management Customer' }).check();
  await page.locator('label').filter({ hasText: 'Kitchen Operations Kitchen' }).click();
  await page.locator('label').filter({ hasText: 'Reports & Analytics Business' }).click();
  await page.locator('label').filter({ hasText: 'System Administration System' }).click();
  await page.getByPlaceholder('0.00').click();
  await page.getByPlaceholder('0.00').fill('350000');
  await page.getByPlaceholder('0.00').press('ArrowLeft');
  await page.getByPlaceholder('0.00').press('ArrowLeft');
  await page.getByPlaceholder('0.00').press('ArrowLeft');
  await page.getByPlaceholder('0.00').press('ArrowRight');
  await page.getByPlaceholder('0.00').press('ArrowLeft');
  await page.getByPlaceholder('0.00').press('ArrowLeft');
  await page.getByPlaceholder('0.00').press('ArrowRight');
  await page.getByPlaceholder('0.00').press('ArrowRight');
  await page.getByPlaceholder('0.00').press('ArrowRight');
  await page.getByPlaceholder('0.00').press('ArrowRight');
  await page.getByPlaceholder('0.00').press('ArrowRight');
  await page.getByPlaceholder('0.00').fill('35000.00');
  await page.getByRole('button', { name: ' Create Plan' }).click();
  await page.getByRole('link', { name: ' Organizations ' }).click();
  await page.getByText('+ Add Organization').click();
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="name"]').fill('Test-Organization');
  await page.locator('input[name="name"]').press('Tab');
  await page.getByRole('textbox', { name: 'example@email.com' }).fill('torg@mail.com');
  await page.getByRole('textbox', { name: 'example@email.com' }).press('Tab');
  await page.locator('input[name="phone"]').fill('0712345678');
  await page.locator('input[name="phone"]').press('Tab');
  await page.locator('#password').fill('Password@123');
  await page.locator('#password').press('Tab');
  await page.locator('#password_confirmation').fill('Password@123');
  await page.locator('#password_confirmation').press('Tab');
  await page.getByRole('textbox', { name: 'Line 1 Line 2 Line 3 Line' }).fill('addres-090');
  await page.getByRole('textbox', { name: 'Line 1 Line 2 Line 3 Line' }).press('Tab');
  await page.locator('input[name="contact_person"]').fill('Ruwan Kumara');
  await page.locator('input[name="contact_person"]').press('Tab');
  await page.locator('input[name="contact_person_designation"]').fill('Owner');
  await page.locator('input[name="contact_person_designation"]').press('Tab');
  await page.locator('input[name="contact_person_phone"]').fill('0712345678');
  await page.locator('select[name="is_active"]').selectOption('1');
  await page.getByRole('button', { name: 'Create Organization' }).click();
  await page.getByRole('link', { name: ' Back to List' }).click();
  await page.getByRole('link', { name: ' Branches ' }).click();
  await page.getByRole('link', { name: 'View' }).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Copy' }).click();
  await page.getByRole('link', { name: ' Branches ' }).click();
  await page.getByRole('link', { name: ' Activate Branch' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('icT0PPcjAmAuboI2jKuIJtxUxzPMyHGb3Ej3QzKN');
  await page.getByRole('button', { name: 'Activate' }).click();
  await expect(page.getByRole('main')).toContainText('Branch activated successfully!');
  await page.getByRole('link', { name: '← Back to Branches' }).click();
  await page.getByRole('link', { name: '+ Add Branch' }).click();
  await page.getByRole('textbox', { name: 'e.g. Main Branch' }).click();
  await page.getByRole('textbox', { name: 'e.g. Main Branch' }).fill('Second Branch');
  await page.getByRole('textbox', { name: 'e.g. Main Branch' }).press('Tab');
  await page.getByRole('textbox', { name: 'e.g. 123 Main St, City' }).fill('Addres @ ');
  await page.getByRole('textbox', { name: 'e.g. 123 Main St, City' }).press('ControlOrMeta+ArrowLeft');
  await page.getByRole('textbox', { name: 'e.g. 123 Main St, City' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'e.g. 123 Main St, City' }).fill('Address @ ');
  await page.getByRole('textbox', { name: 'e.g. 123 Main St, City' }).press('ControlOrMeta+ArrowRight');
  await page.getByRole('textbox', { name: 'e.g. 123 Main St, City' }).fill('Address @ secon branch ');
  await page.getByRole('textbox', { name: 'e.g. 123 Main St, City' }).press('Tab');
  await page.locator('input[name="phone"]').fill('0712345678');
  await page.locator('input[name="opening_time"]').click();
  await page.locator('input[name="opening_time"]').fill('08:00');
  await page.locator('input[name="closing_time"]').click();
  await page.locator('input[name="closing_time"]').press('ArrowLeft');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowRight');
  await page.locator('input[name="closing_time"]').fill('22:00');
  await page.locator('input[name="closing_time"]').press('ArrowRight');
  await page.locator('input[name="closing_time"]').press('ArrowDown');
  await page.locator('input[name="closing_time"]').press('ArrowUp');
  await page.locator('input[name="closing_time"]').press('Tab');
  await page.locator('input[name="closing_time"]').press('Tab');
  await page.getByPlaceholder('e.g. 50', { exact: true }).click();
  await page.getByPlaceholder('e.g. 50', { exact: true }).fill('60');
  await page.getByPlaceholder('e.g. 100.00').click();
  await page.getByPlaceholder('e.g. 100.00').fill('100');
  await page.getByPlaceholder('e.g. 50.00').click();
  await page.getByPlaceholder('e.g. 50.00').fill('50');
  await page.getByRole('textbox', { name: 'e.g. John Doe' }).click();
  await page.getByRole('textbox', { name: 'e.g. John Doe' }).fill('Sec Contact');
  await page.getByRole('textbox', { name: 'e.g. John Doe' }).press('Tab');
  await page.getByRole('textbox', { name: 'e.g. Manager' }).fill('Manager');
  await page.locator('input[name="contact_person_phone"]').click();
  await page.locator('input[name="contact_person_phone"]').fill('0712345678');
  await page.getByRole('button', { name: 'Create Branch' }).click();
  await page.getByRole('link', { name: 'View' }).nth(1).click();
  page.once('dialog', dialog => {
    console.log(`Dialog message: ${dialog.message()}`);
    dialog.dismiss().catch(() => {});
  });
  await page.getByRole('button', { name: 'Copy' }).click();
  await page.getByRole('link', { name: ' Branches 1 ' }).click();
  await page.getByRole('link', { name: ' Activate Branch' }).click();
  await page.getByRole('textbox').click();
  await page.getByRole('textbox').fill('8WTz3qy7ISBJ1swEx5ChragYNzJ2zTXKqgB4PfkH');
  await page.getByRole('button', { name: 'Activate' }).click();
  await page.getByRole('link', { name: '← Back to Branches' }).click();
  await page.getByRole('link', { name: 'View' }).first().click();
  await page.getByRole('link', { name: '+ Create User' }).first().click();
  await page.getByLabel('Organization').selectOption('1');
  await page.getByLabel('Branch (Optional)').selectOption('1');
  await page.getByLabel('Role').selectOption('2');
  await page.getByRole('textbox', { name: 'Full Name' }).click();
  await page.getByRole('textbox', { name: 'Full Name' }).fill('Org - Staff Member - 001');
  await page.getByRole('textbox', { name: 'Full Name' }).press('Tab');
  await page.getByRole('textbox', { name: 'Email' }).fill('staff-org1@mail.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter password', exact: true }).fill('Password@123');
  await page.getByRole('textbox', { name: 'Enter password', exact: true }).press('Tab');
  await page.getByRole('textbox', { name: 'Re-enter password' }).fill('Password@123');
  await page.getByRole('button', { name: 'Create User' }).click();
  await page.goto('https://restaurent-management-sysytem.test/admin/users/create?organization=1&branch=1');
  await page.getByRole('link', { name: ' User Management 2 ' }).click();
  await page.getByRole('link', { name: ' Suppliers ' }).click();
  await page.getByRole('link', { name: '+ Add New Supplier' }).click();
  await page.getByLabel('Organization *').selectOption('1');
  await page.getByRole('textbox', { name: 'Company Name *' }).click();
  await page.getByRole('textbox', { name: 'Company Name *' }).fill('Supplier - Company - 001');
  await page.getByRole('checkbox', { name: 'Has VAT Registration' }).check();
  await page.getByRole('textbox', { name: 'VAT Registration Number' }).click();
  await page.getByRole('textbox', { name: 'VAT Registration Number' }).fill('VAT-0123456789');
  await page.getByRole('textbox', { name: 'Company Address' }).click();
  await page.getByRole('textbox', { name: 'Company Address' }).fill('Address @ 098');
  await page.getByRole('button', { name: 'Next: Contact Details ' }).click();
  await page.getByRole('textbox', { name: 'Contact Person *' }).click();
  await page.getByRole('textbox', { name: 'Contact Person *' }).fill('Supplier Contact Person -001');
  await page.getByRole('textbox', { name: 'Contact Person *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Contact Person *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Contact Person *' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Contact Person *' }).fill('Supplier Contact Person - 001');
  await page.getByRole('textbox', { name: 'Phone *' }).click();
  await page.getByRole('textbox', { name: 'Phone *' }).fill('0712345678');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('SUPcon@mail.com');
  await page.getByRole('button', { name: 'Create Supplier' }).click();
  await page.getByRole('link', { name: ' Inventory ' }).click();
  await page.getByRole('link', { name: '+ New Item' }).click();
  await page.getByLabel('Target Organization *').selectOption('1');
  await page.getByRole('textbox', { name: 'Enter item name' }).click();
  await page.getByRole('textbox', { name: 'Enter item name' }).fill('Basmati Rice');

  await page.getByRole('textbox', { name: 'Enter unicode name' }).click();
  await page.getByRole('textbox', { name: 'Enter unicode name' }).fill('බස්මති බත්');
  await page.getByRole('textbox', { name: 'Enter item code' }).click();
  await page.getByRole('textbox', { name: 'Enter item code' }).fill('CARB-001');
  await page.locator('select[name="items[0][item_category_id]"]').selectOption('3');
  await page.locator('select[name="items[0][unit_of_measurement]"]').selectOption('kg');
  await page.getByPlaceholder('Minimum stock level').click();
  await page.getByPlaceholder('Minimum stock level').fill('25');
  await page.locator('input[name="items[0][buying_price]"]').click();
  await page.locator('input[name="items[0][buying_price]"]').fill('1500');
  await page.locator('input[name="items[0][buying_price]"]').press('Tab');
  await page.locator('input[name="items[0][selling_price]"]').fill('0');
  await page.locator('input[name="items[0][selling_price]"]').press('Tab');
  await page.getByPlaceholder('Expiry period in days').fill('120');
  await page.getByPlaceholder('Expiry period in days').press('Tab');
  await page.getByRole('textbox', { name: 'Detailed item description' }).fill('Premium Indian basmati rice');
  await page.getByRole('textbox', { name: 'Detailed item description' }).press('Tab');
  await page.getByRole('textbox', { name: 'Any special notes about this' }).fill('Store In Dry Place');
  await page.getByRole('textbox', { name: 'Any special notes about this' }).press('Tab');
  await page.locator('select[name="items[0][item_type]"]').selectOption('buy_sell');
  await page.getByRole('button', { name: ' Save All Items' }).click();
  await page.getByRole('link', { name: '+ Add More Items' }).click();
  await page.getByLabel('Target Organization *').selectOption('1');
    await page.getByRole('textbox', { name: 'Enter item name' }).click();
    await page.getByRole('textbox', { name: 'Enter item name' }).fill('Red Rice');
    await page.getByRole('textbox', { name: 'Enter unicode name' }).click();
    await page.getByRole('textbox', { name: 'Enter unicode name' }).fill('රතු බත්');
    await page.getByRole('textbox', { name: 'Enter item code' }).click();
    await page.getByRole('textbox', { name: 'Enter item code' }).fill('CARB-002');
    await page.locator('select[name="items[0][item_category_id]"]').selectOption('3');
    await page.locator('select[name="items[0][unit_of_measurement]"]').selectOption('kg');
    await page.getByPlaceholder('Minimum stock level').click();
    await page.getByPlaceholder('Minimum stock level').fill('25');
    await page.locator('input[name="items[0][buying_price]"]').click();
    await page.locator('input[name="items[0][buying_price]"]').fill('1250');
    await page.locator('input[name="items[0][selling_price]"]').click();
    await page.locator('input[name="items[0][selling_price]"]').fill('0');
    await page.getByPlaceholder('Expiry period in days').click();
    await page.getByPlaceholder('Expiry period in days').fill('120');
    await page.getByRole('textbox', { name: 'Detailed item description' }).click();
    await page.getByRole('textbox', { name: 'Detailed item description' }).fill('Local red rice 1kg packs');
    await page.getByRole('textbox', { name: 'Any special notes about this' }).click();
    await page.getByRole('textbox', { name: 'Any special notes about this' }).fill('Store in a Dry Place');
    await page.locator('select[name="items[0][item_type]"]').selectOption('buy_sell');
    await page.getByRole('button', { name: ' Save All Items' }).click();
    await page.getByRole('link', { name: ' Back to Items' }).click();
});
