name: Gemini AI Code Reviewer

on:
  issue_comment:
    types: [created]
permissions: write-all
jobs:
  gemini-code-review:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/ai-review')
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run Gemini AI Code Reviewer
        uses: HoangNguyen0403/ai_code_reviewer@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AI_MODEL: 'gemini-2.5-flash-preview-05-20' 
          FILES_EXCLUDE: ['**/node_modules/**', '**/dist/**', '**/build/**']
